### PR TITLE
Make it possible to edit values in table

### LINKED ISSUE #28: Is there an Editor extension available for the DT package
I love this package. I combined several extensions and it really helps my app look great and function.

I thought KeyTable would allow me to edit, but it just navigates and highlights.

Is there an editor extension available or coming soon.

Thanks!
Mike

### PR DESCRIPTION
**Pull request by yihui**
Closes #28

## Test

```r
devtools::install_github('rstudio/DT@feature/editor')
```

Double click in a table cell to edit its value.

## (1) client-side processing (static HTML application)

```r
DT::datatable(iris)
```

## (2) client-side processing in Shiny

```r
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(
    DT::dataTableOutput('x2')
  ),
  server = function(input, output, session) {
    x = iris
    x$Date = Sys.time() + seq_len(nrow(x))
    output$x2 = DT::renderDataTable(x, selection = 'none', server = FALSE)
  }
)
```

## (3) server-side processing

```r
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(
    DT::dataTableOutput('x1')
  ),
  server = function(input, output, session) {
    x = iris
    x$Date = Sys.time() + seq_len(nrow(x))
    output$x1 = DT::renderDataTable(x, selection = 'none')
    
    proxy = dataTableProxy('x1')
    
    observeEvent(input$x1_cell_edit, {
      info = input$x1_cell_edit
      str(info)
      i = info$row
      j = info$col
      v = info$value
      x[i, j] <<- DT::coerceValue(v, x[i, j])
      replaceData(proxy, x, resetPaging = FALSE)  # important
    })
  }
)
```

## (4) server-side processing (without row names)

```r
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(
    DT::dataTableOutput('x1')
  ),
  server = function(input, output, session) {
    x = iris
    x$Date = Sys.time() + seq_len(nrow(x))
    output$x1 = DT::renderDataTable(x, selection = 'none', rownames = FALSE)
    
    proxy = dataTableProxy('x1')
    
    observeEvent(input$x1_cell_edit, {
      info = input$x1_cell_edit
      str(info)
      i = info$row
      j = info$col + 1  # column index offset by 1
      v = info$value
      x[i, j] <<- DT::coerceValue(v, x[i, j])
      replaceData(proxy, x, resetPaging = FALSE, rownames = FALSE)
    })
  }
)
```

### CODE REVIEW

**Comment by yihui** [comment]
@tamluong Your `output$text` should be dependent on `input$x1_cell_edit`, otherwise when you edit a cell, it won't be automatically updated. This should work:

```r
    output$text <- renderText({
        input$x1_cell_edit
        x[1, 1]
    })
```

Note you don't need `y()`, because `x` has been updated via `<<-`.

**Comment by tamluong** [comment]
@yihui Thank you! That works perfectly. One thing I noticed is that although y is an reactive expression based on x, y is not automatically updated when x is changed. Was that because Shiny does not recognize x as an input value?

**Comment by yihui** [comment]
@tamluong That is because although `y()` was created by `reactive()`, it is not literally reactive to any inputs. You meant to make it reactive to the edit event, but you didn't state the dependency in its definition. For example, you can associate `input$x1_cell_edit` with `y()`:

```r
server <- function(input, output, session) {
    x = iris
    y <- reactive({
      input$x1_cell_edit
      x
    })
    x$Date = Sys.time() + seq_len(nrow(x))
    output$x1 = DT::renderDataTable(x, selection = 'none', editable = TRUE)
    
    proxy = dataTableProxy('x1')

    observeEvent(input$x1_cell_edit, {
        info = input$x1_cell_edit
        str(info)
        i = info$row
        j = info$col
        v = info$value
        x[i, j] <<- DT::coerceValue(v, x[i, j])
        replaceData(proxy, x, resetPaging = FALSE)  # important
    })
    
    output$text <- renderText({
        y()[1, 1]
    })
}
```

Or make `output$text` reactive to `input$x1_cell_edit` this way (note `y` does not need to be reactive):

```r
server <- function(input, output, session) {
    x = iris
    y <- function() x
    x$Date = Sys.time() + seq_len(nrow(x))
    output$x1 = DT::renderDataTable(x, selection = 'none', editable = TRUE)
    
    proxy = dataTableProxy('x1')

    observeEvent(input$x1_cell_edit, {
        info = input$x1_cell_edit
        str(info)
        i = info$row
        j = info$col
        v = info$value
        x[i, j] <<- DT::coerceValue(v, x[i, j])
        replaceData(proxy, x, resetPaging = FALSE)  # important
    })
    
    output$text <- renderText({
        input$x1_cell_edit
        y()[1, 1]
    })
}
```

**Comment by tamluong** [comment]
@yihui that makes perfect sense! Thanks so much!

**Comment by KaterinaKou** [comment]
Hello!
Is there a workaround to make only certain columns editable?

**Comment by zackbatist** [comment]
The coerceValue command is giving me the following error, since according to the docs it only works with integer, double, date, time and factor values:
‘’’
Warning in DT::coerceValue(v, x[i, j]) :
The data type is not supported: character
‘’’

The data that i want the user to edit are character values. Any suggestions for a workaround would be immensely appreciated!

**Comment by yihui** [comment]
@zackbatist #542

```r
devtools::install_github('rstudio/DT')
```

**Comment by adiguzelomer** [comment]
Is there any update on KaterinaKou' s question ?
"
Hello!Is there a workaround to make only certain columns editable?
"
I am looking forward to it too. O.O

**Comment by yihui** [comment]
@adiguzelomer No: #550.

**Comment by KaterinaKou** [comment]
@adiguzelomer 
if you're still looking for a workaround,

```
fooreactive<-reactiveValues(foovalue={
       #Some kind of dataframe you show on a DT table
}
output$DToutput<-DT::renderDataTable({
        fooreactive[["foovalue"]]
}, editable = TRUE)  #Your DT output
      
proxy = DT::dataTableProxy('DToutput')  #Your DT proxy
      
observeEvent(input$DToutput_cell_edit, {
        info = input$DToutput_cell_edit
        str(info)
        i = info$row
        j = info$col + 1  # column index offset by 1
        v = info$value
        if(j == 3){ #This is the column you want to have as editable
          fooreactive[["foovalue"]]$nameofeditcolumn[i] <- DT::coerceValue(v, fooreactive[["foovalue"]]$nameofcolumn[i])
          rep<-fooreactive[["foovalue"]]
          DT::replaceData(proxy, rep, resetPaging = FALSE, rownames = FALSE)
        }
})

**Comment by yihui** [comment]
@philibe Currently it is not straightforward, and it may require deeper understanding of the implementation of server-side processing in this package. I did think about wider support for SQL long time ago (see #194), but haven't found time to actually do the work. It will definitely be amazing if all basic SQL operations can be supported in DT (in particular, querying/filtering should be much much faster). Your example is a very good start.

**Comment by philibe** [comment]
:+1: :)

**Comment by adiguzelomer** [comment]
@KaterinaKou thank you alot ! I am gonna try it.

**Comment by zackbatist** [comment]
Thanks @yihui, you're of great help. I also agree with @philibe, such SQL functionality would be extremely useful!

**Comment by ddelarosa70** [comment]
is there a way to use the all the extensions that DT have a long with the editing. ie. fixed columns, hiding columns etc.


As far as I can tell and test there is only 
output$x <- DT::renderDT( data, selection = 'none', server = F, editable = T )

if I try to use an expression to calculate the data and return datatable with the extensions, the editing is ignored , and viceversa

**Comment by stamatelou** [comment]
Hi! Is there any way that editable= TRUE for specific columns and not for the whole datatable?

**Comment by adityaraj04** [comment]
how to write/save the file after making changes to it?

**Comment by Bidossessih** [comment]
Hi @yihui ,
I would like to know how to enable the value edition in small device browser. I tried your example (https://yihui.shinyapps.io/DT-edit/) in mobile phone but I can't edit the table. It works perfectly when accessing from my computer. I need this functionality in an app optimized for small device. Thanks.

**Comment by nschwamm** [comment]
> @tamluong That is because although `y()` was created by `reactive()`, it is not literally reactive to any inputs. You meant to make it reactive to the edit event, but you didn't state the dependency in its definition. For example, you can associate `input$x1_cell_edit` with `y()`:
> 
> ```r
> server <- function(input, output, session) {
>     x = iris
>     y <- reactive({
>       input$x1_cell_edit
>       x
>     })
>     x$Date = Sys.time() + seq_len(nrow(x))
>     output$x1 = DT::renderDataTable(x, selection = 'none', editable = TRUE)
>     
>     proxy = dataTableProxy('x1')
> 
>     observeEvent(input$x1_cell_edit, {
>         info = input$x1_cell_edit
>         str(info)
>         i = info$row
>         j = info$col
>         v = info$value
>         x[i, j] <<- DT::coerceValue(v, x[i, j])
>         replaceData(proxy, x, resetPaging = FALSE)  # important
>     })
>     
>     output$text <- renderText({
>         y()[1, 1]
>     })
> }
> ```
> 
> Or make `output$text` reactive to `input$x1_cell_edit` this way (note `y` does not need to be reactive):
> 
> ```r
> server <- function(input, output, session) {
>     x = iris
>     y <- function() x
>     x$Date = Sys.time() + seq_len(nrow(x))
>     output$x1 = DT::renderDataTable(x, selection = 'none', editable = TRUE)
>     
>     proxy = dataTableProxy('x1')
> 
>     observeEvent(input$x1_cell_edit, {
>         info = input$x1_cell_edit
>         str(info)
>         i = info$row
>         j = info$col
>         v = info$value
>         x[i, j] <<- DT::coerceValue(v, x[i, j])
>         replaceData(proxy, x, resetPaging = FALSE)  # important
>     })
>     
>     output$text <- renderText({
>         input$x1_cell_edit
>         y()[1, 1]
>     })
> }
> ```

For this example, how would you replicate it, if the datatable itself was based on a reactive value. Let's say we just binded iris and input$test as a dataframe. Where selectInput("test",choices=c(TRUE,FALSE), so it's just a binary choice and the last column of Iris is an editable column that's initial values are based on an input?

Obviously a more complicated example wouldn't just spit out the input but I am trying to understand how you can use editable DT as well as the values from it to persist when the underlying data is dependent on inputs.

**Comment by anapaularg** [comment]
> @adiguzelomer
> if you're still looking for a workaround,
> 
> ```
> fooreactive<-reactiveValues(foovalue={
>        #Some kind of dataframe you show on a DT table
> }
> output$DToutput<-DT::renderDataTable({
>         fooreactive[["foovalue"]]
> }, editable = TRUE)  #Your DT output
>       
> proxy = DT::dataTableProxy('DToutput')  #Your DT proxy
>       
> observeEvent(input$DToutput_cell_edit, {
>         info = input$DToutput_cell_edit
>         str(info)
>         i = info$row
>         j = info$col + 1  # column index offset by 1
>         v = info$value
>         if(j == 3){ #This is the column you want to have as editable
>           fooreactive[["foovalue"]]$nameofeditcolumn[i] <- DT::coerceValue(v, fooreactive[["foovalue"]]$nameofeditcolumn[i])
>           rep<-fooreactive[["foovalue"]]
>           DT::replaceData(proxy, rep, resetPaging = FALSE, rownames = FALSE)
>         }
> })
> ```

Hi @adiguzelomer, this worked for you? I tried to replicate your solution but what I see is that the "user" still could **click** and **edit** a cell that is not in the column 3, and when doing "enter" the new value stays in the table. Only when trying to edit column 3, the other values previously changed return to their original value. This is really weird for the user. Maybe I'm doing something wrong. Did you get a solution where the user can't double click and edit the cell?

**Comment by yihui** [comment]
For those who want to disable editing on certain columns, I just pushed an implementation through 832714f. Thanks!

**Comment by PeterDieter** [comment]
Hello:) As @rajkumarmaniraja57 already asked, is there a way how I can change a value in a data table that can be filtered based on inputs. So is filtering and editing possible at the same time?
Thanks @yihui

**Comment by yihui** [comment]
@PeterDieter No, that is currently not possible. Sorry.

**Comment by antoine-sachet** [comment]
Is it still "important" to run `replaceData` in the observer?

The example seems to work just fine without `replaceData(proxy, x, resetPaging = FALSE)`, and it actually avoids a flicker. 

If it can be safely avoided, it makes it easier to use a proxy in a shiny module (no need to pass the global session to the proxy).

```r
library(shiny)
library(DT)
shinyApp(
  ui = fluidPage(
    DTOutput('x1')
  ),
  server = function(input, output, session) {
    x = iris
    x$Date = Sys.time() + seq_len(nrow(x))
    output$x1 = renderDT(x, selection = 'none', editable = TRUE)
    
    proxy = dataTableProxy('x1')
    
    observeEvent(input$x1_cell_edit, {
      info = input$x1_cell_edit
      str(info)
      i = info$row
      j = info$col
      v = info$value
      x[i, j] <<- DT::coerceValue(v, x[i, j])
      # Code works just fine without the line below
      # replaceData(proxy, x, resetPaging = FALSE)  # important
    })
  }
)
```

**Comment by yihui** [comment]
@antoine-sachet Without `replaceData()`, the new value only lives in your browser. If you navigate to a different page of the table, then come back, the edited value will be lost (you will see the old value). This is because `renderDT()` does not know `x` has been modified, and will still render the old copy of `x`.

**Comment by Stephonomon** [comment]
Hi, this is great! Everything works except that after the data are saved, the table displaying the information goes blank and DT says No Matching Records Found, however, if I reload the page, the saved data is there.

```
shinyServer(function(input, output) {
  ds <<- redcap_read(redcap_uri=uri, token=token)$data
  
  output$redcaptable = renderDataTable({
    ds <<- redcap_read(redcap_uri=uri, token=token)$data
    ds <- datatable(ds,
                    editable = TRUE
                    )
  })
  
  proxy = dataTableProxy('redcaptable')
  
  observeEvent(input$redcaptable_cell_edit, {
    info = input$redcaptable_cell_edit
    str(info)
    i = info$row
    j = info$col
    v = info$value 
    ds[i, j] <<- DT::coerceValue(v, ds[i, j])
    replaceData(proxy, ds, resetPaging = TRUE, rownames = FALSE)
    redcap_write(ds,redcap_uri=uri,token=token)
    ds
#ds <<- redcap_read(redcap_uri=uri, token=token)$data
  })
#tried with and without the read_cap read (pulls from API), but no luck
```

**Comment by jumanbar** [comment]
This functionality is great.

In my case, I have a small problem regarding the characters ">" and "<". When using client-side processing example, I cannot change the content of a cell from "setosa" to "< LD", for example, because that means the contents are no longer visible (I know this example doesn't make much sense, but trust me, it's important for my app). This of course happens because "<" and ">" are reserved HTML characters (if I write "\&lt; LD" the cell contents are shown as intended).

I've noticed that this does not happen when using the example provided for server-side processing. But in that case I have other problems, since my file is provided by the user... **Would it be possible to have the server side functionality even in the case of a file uploaded by the user (using `fileInput`)?**

I attempted some code based on the above example (pasted below) and failed, with the following error message:

    Warning: Error in <<-: invalid (NULL) left side of assignment
      72: observeEventHandler [/home/juan/Desktop/example.R#46]
       1: runApp

Here is my code:

```r
library(shiny)
library(DT)

shinyApp(
  ui = fluidPage(
    fileInput(
      inputId = "upload", 
      label = span(icon("upload"), "Choose csv file:"),
      multiple = FALSE, 
      accept = c("text/csv",
                 "text/comma-separated-values,text/plain",
                 ".csv")),
    DTOutput('x1')
  ),
  server = function(input, output, session) {
    upfile <- reactive({
      req(input$upload)
      tryCatch({
        out <- read.csv(input$upload$datapath, as.is = TRUE)
        out$Date <- Sys.time() + seq_len(nrow(out))
      }, # return a safeError if a parsing error occurs
      error = function(e) stop(safeError(e)) 
      )
      return(out)
    })
    
    output$x1 = renderDT(upfile(), selection = 'none', 
                         server = TRUE, editable = TRUE)
    
    proxy = dataTableProxy('x1')
    
    observeEvent(input$x1_cell_edit, {
      info = input$x1_cell_edit
      str(info)
      i = info$row
      j = info$col
      v = info$value
      # Here I basically changed x with upfile() in all instances:
      upfile()[[j]][i] <<- DT::coerceValue(v, upfile()[[j]][i])
      replaceData(proxy, upfile(), resetPaging = FALSE)  # important
    })
  }
)
```

The file used for my tests was created with:

```r
write.csv(iris, "iris.csv", row.names = FALSE)
```

Thanks for your work and your time!

**Comment by Zemnii** [comment]
Thank you very much it works really fine , however when i affect the table to a reactive one using : 
data=reactive({input$x1_cell_edit
                         return(x)}
it works fine but i get this warning when editing :
Capture

**Comment by shrektan** [comment]
Please open a new issue if you need help or encounter bugs. Leaving comments on a closed PR will be easily missed because it’s difficult to find the entry later.

**Comment by FrancescoGal** [comment]
Hi, I have an issue that I cannot solve.
If I copy your program as it is, and publish it with shinyapps.io,
every edit that I do, it won't be saved and any refresh will cancel all my edits..
how can I permanently edit my dataset?
here you can find my code:

library(shiny)
library(DT)
library(rsconnect)

DTicps <-read.csv("icps.csv", sep=";")
DTicps$Giorno <- as.character(DTicps$Giorno)
DTicps$ICPS1_A <- as.character(DTicps$ICPS1_A)
DTicps$ICPS1_B <- as.character(DTicps$ICPS1_B)
DTicps$ICPS1_C <- as.character(DTicps$ICPS1_C)
DTicps$ICPS1_D <- as.character(DTicps$ICPS1_D)
DTicps$ICPS1_E <- as.character(DTicps$ICPS1_E)
DTicps$ICPS1_F <- as.character(DTicps$ICPS1_F)
DTicps$ICPS2_G <- as.character(DTicps$ICPS2_G)
DTicps$ICPS2_H <- as.character(DTicps$ICPS2_H)
DTicps$ICPS2_I <- as.character(DTicps$ICPS2_I)
DTicps$ICPS2_J <- as.character(DTicps$ICPS2_J)
DTicps
str(DTicps)

shinyApp(
    ui = fluidPage(
        DTOutput('x1')
    ),
    server = function(input, output, session) {
        
        x = DTicps
        x$Date = Sys.time() + seq_len(nrow(x))
        output$x1 = renderDT(x, selection = 'none', editable = TRUE)
        
        proxy = dataTableProxy('x1')
        
        observeEvent(input$x1_cell_edit, {
            info = input$x1_cell_edit
            str(info)
            i = info$row
            j = info$col
            v = info$value
            x[i, j] <<- DT::coerceValue(v, x[i, j])
            replaceData(proxy, x, resetPaging = F)  # important
        })
    }
)

**Pull request merged**
