### PR TITLE
Default to style='auto' which uses bootstrap styling when a bootstraplib theme is active

### PR DESCRIPTION
**Pull request by cpsievert**
This PR changes the default value of `datatable()`'s `style` argument to `'auto'`, which resolves to either `'bootstrap'` or `'bootstrap4'` when a `{bslib}` theme is active (if no theme is active, it resolves to `'default'`). 

This is primarily so that `{DT}` works out-of-the-box with  Shiny + `{bslib}`:

```r
library(shiny)
library(DT)

ui <- fluidPage(
  theme = bslib::bs_theme(
    bg = "#002B36", fg = "#EEE8D5", primary = "#2AA198"
  ),
  dataTableOutput("x")
)

server <- function(input, output, session) {
  output$x <- renderDataTable({
    datatable(mtcars)
  })
}

shinyApp(ui, server)
```

Screen Shot 2020-09-04 at 5 12 17 PM

As well as R Markdown + `{bslib}`:

````
---
output:
  html_document:
    theme:
      bg: "#002B36" 
      fg: "#EEE8D5"
      primary: "#2AA198"
---

```{r}
DT:::datatable(mtcars)
```
````

Or even, more generally, when a `{bslib}` theme is set globally:

```r
bslib::bs_global_theme(bg = "#002B36", fg = "#EEE8D5", primary = "#2AA198")
DT:::datatable(mtcars)
```

### CODE REVIEW

**Review by yihui — APPROVED** [review]
Looks good to me. Sounds like we need to wait for **bootstraplib** to appear on CRAN before we could merge this PR? Thanks!

**Comment by cpsievert** [comment]
Yea, but if you're ok with a **bootstraplib** CRAN release (hopefully about a month away) blocking a **DT** CRAN release, then feel free to merge as is

**Comment by yihui** [comment]
We'll probably make a **DT** release before that, so let's merge this after **bootstraplib**'s CRAN release.

**Review by shrektan — APPROVED** [review]
LGTM. Thanks.

**Comment by cpsievert** [comment]
Unfortunately, I think we might have to go with the https://github.com/rstudio/DT/pull/740 direction instead of this one since the datatable CSS isn't smart enough to properly contrast accent colors

**Comment by cpsievert** [comment]
@shrektan @yihui feel free to merge (bslib and shiny are both now on CRAN)!

**Review by yihui — APPROVED** [review]
Great. Thanks!

**Pull request merged**
