### PR TITLE
The numbers editing now return a number instead of a string (#986)

### PR DESCRIPTION
**Pull request by stla**
Test:

```r
library(shiny)
library(DT)

callback <- c(
  '$("#show").on("click", function(){',
  '  var headers = Array.from(table.columns().header()).map(x => x.innerText);',
  '  var arrayOfColumns = Array.from(table.columns().data());',
  '  var rownames = arrayOfColumns[0]',
  '  headers.shift(); arrayOfColumns.shift();',
  '  var entries = headers.map((h, i) => [h, arrayOfColumns[i]]);',
  '  var columns = Object.fromEntries(entries);',
  '  Shiny.setInputValue(',
  '    "tabledata", {rownames: rownames, columns: columns}, {priority: "event"}',
  '  );',
  '});'
)

ui <- fluidPage(
  br(),
  DTOutput("dtable"),
  br(),
  tags$h3("Edit a cell and click"),
  actionButton("show", "Print data")
)


server <- function(input, output) {
  
  dat <- data.frame(x=c(0,1),
                    y=c(0,1))
  
  output[["dtable"]] <- renderDT({
    datatable(
      dat, 
      editable = TRUE,
      callback = JS(callback)
    )
  }, server = FALSE)
  
  observeEvent(input[["tabledata"]], {
    columns <- lapply(input[["tabledata"]][["columns"]], unlist)
    df <- as.data.frame(columns)
    rownames(df) <- input[["tabledata"]][["rownames"]]
    print(str(df))
  })
  
}

shinyApp(ui = ui, server = server)
```

### CODE REVIEW

**Review by yihui — COMMENTED** [review]
It seems that you need to adjust your git CRLF config? https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by stla** [comment]
Thanks yihui.

Sorry but it seems that there's no attached jQuery dependency outside Shiny. Then my code cannot work outside Shiny...

**Comment by stla** [comment]
Wait, I'm lost now. I see there is jQuery when I inspect the document. However I get the error `$ not defined`. Why that?

**Comment by stla** [comment]
Ah I think I have to place this jQuery code in `HTMLWidgets.widget(...)`. I gonna try now.

**Comment by stla** [comment]
Ok, I believe everything is correct now.

**Comment by yihui** [comment]
Thanks, but the CRLF issue I mentioned above is not resolved. If you look at the "Files changed" pane (https://github.com/rstudio/DT/pull/987/files), you can see that the diffs are not clear (as if you changed the whole file).

**Comment by stla** [comment]
Ah, I didn't understand this was an issue. I followed the instructions given in your link, but maybe this was too late.

**Comment by yihui** [comment]
No worries. I just fixed it by myself. Hopefully next time it will be correct. Thanks!

**Pull request merged**
