### PR TITLE
Add limits and angle parameters to styleColorBar

### PR DESCRIPTION
**Pull request by ReportMort**
Add limits parameter allows user to specify the min and max values to represent as 0 and 100 filled bars

Add angle parameter allows user to specify the direction of the gradient fill

### CODE REVIEW

**Comment by yihui** [comment]
Thanks for the PR. As explained in #113, I don't think the `limits` argument is necessary. For `angle`, I guess only -90 and 90 make sense?

BTW, before I can possibly accept your PR, you will need to sign a contributor agreement if you haven't done so: https://github.com/rstudio/shiny/blob/master/CONTRIBUTING.md

**Comment by ReportMort** [comment]
Thanks for explaining in #113. That is very clever to pass the limits as the data argument. 

I've removed the proposed limits argument and tried to make that more clear in the documentation. I have submitted a contributor agreement to JJ, so if you are okay with the changes, then feel free to merge.

By the way, thank you for all your hard work. Some of the packages you've created have completely changed how I use R and have inspired me to contribute and become more involved.

**Comment by yihui** [comment]
I think I'm okay with this PR. Can you try `angle = -90` and make sure it works as expected? Other than that, I'm just waiting for the green light from @jjallaire. Thanks!

**Comment by ReportMort** [comment]
Angle parameter -90 works (as well as other variations). Please see example here: https://reportmort.shinyapps.io/DT-colorbar

**Comment by yihui** [comment]
Fantastic. Thanks again.

**Pull request merged**
