### PR TITLE
support shift+click to select mutiple rows

### LINKED ISSUE #305: Feature request: Selecting multiple rows using shift+click
Thank you for the wonderful package.

It would be very useful to be able to select multiple rows using shift+click instead of having to click each
row individually.

I see that this has been asked for [previously](https://groups.google.com/forum/#!topic/shiny-discuss/PdhVoX0FJlU).

### PR DESCRIPTION
**Pull request by shrektan**
closes #305

### CODE REVIEW

**Comment by shrektan** [comment]
Here's my testing code.

```r
library(shiny)

server <- function(input, output) {
  output$data <- DT::renderDT(
    DT::datatable(iris), server = F
  )
  output$data_sel <- renderText(input$data_rows_selected)
}
ui <- fluidPage(
  tagList(
    DT::DTOutput("data"),
    textOutput("data_sel")
  )
)

shinyApp(ui, server, options = list(port = 7995))

```

**Comment by yihui** [comment]
I have fixed the text selection issue. The other thing is that this probably does not work in the server-processing mode (which is always tricky in DT)...

**Comment by shrektan** [comment]
Well, just confirm that there's indeed a small issue (seem like small), which is the selection range will be different between the server-processing mode and the client side mode.

1. select first row in page 1, let's assume it's row no 1;
1. press <kbd>shift</kbd>
1. select another row in another page, let's assume it's row no 20, and every page displays 5 row

In the client side mode, the row selection will be 1 to 20, while in the server-processing mode, it's 1, 16 to 20...

**Comment by yihui** [comment]
You need to use the vector `DT_rows_current` to convert the local row index to the index on the server side. You can see how I did it in `changeInput('rows_selected')` and `changeInput('row_last_clicked')`. Let me know if you are able to fix it. Thanks!

**Comment by shrektan** [comment]
I guess I should be able to fix it based on your current code, some ideas on server-processing mode:

+ `lastClickedRow` and `currentClickedRow` (i.e., `thisRow.index()`) should be converted to the index on server side;
+ `shiftSelRows()` should return the indexes on server side as well. Since on client side, the browser itself doesn't know what the real underlying data is, we can only convert the indexes relying on `DT_rows_current`.
+ Select the rows based on server side indexes. Here's the tricky part, how can I be able to select rows that hasn't been loaded to the browsers yet? By looking at your implementation for [`selection = list(mode = "multiple", selected = c(1, 3, 8)`](https://github.com/shrektan/DT/blob/421c18da7503942a486f9f7dfbd84506dcff62e6/inst/htmlwidgets/datatables.js#L826-L835)  I think it can be done by changing the value of `selected1`.

Will try to fix it tonight or tomorrow~

**Comment by yihui** [comment]
Sounds great!

**Comment by yihui** [comment]
我的 0.3 版本计划的事项现在还剩下两项：https://github.com/rstudio/DT/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.3 我先做 #28 去了，你这个事项需要比较细心的考虑，所以你慢慢来不着急，下周之前能捣鼓出来最好，捣鼓不出来也没事。多谢！

**Comment by shrektan** [comment]
恩恩，白天上班没什么时间 :man_office_worker: 

昨天稍微鼓捣了下，要是没有幺蛾子的话，感觉应该可以弄出来。因为没有测试嘛，代码有无其他坏的影响，姑且只能由你来把关啦，哈哈哈。

**Comment by yihui** [comment]
嗯，我也只能用意念力在脑子里“测试”。

**Pull request merged**
