### PR TITLE
Column filter spacing + custom dataTablesJSON function

### PR DESCRIPTION
**Pull request by vnijs**
@yihui I tried a few things to see if I could increase the spacing in the column filter boxes. For some reason the padding on the right is currently really high. I removed the form-control class in a few places and, even though the look is not that stylish, the spacing is much improved. With these changes issue #49 also does not occur which is a nice side-effect. I actually like the remove-circle below the box. See the Data > View tab at http://vnijs.rady.ucsd.edu:3838/base (Data > View tab) for the alternative 'look'

I also added an argument to `dataTableAjax` to make it easier to create a custom `dataTablesJSON` function - #66.

Any suggestions on how to make the sliders a bit coarser? It is currently very hard to get to a whole number which is what a user would most likely want, especially for integers.

### CODE REVIEW

**Comment by yihui** [comment]
Thanks! The new argument for `dataTablesAjax()` is fine. I need to think more about what to do with the clear button and the step length of the slider.

BTW, if you have not signed the CLA for RStudio before, here is what you need to do before we can accept your pull requests to RStudio's Github repositories: https://github.com/rstudio/shiny/blob/master/CONTRIBUTING.md

**Comment by vnijs** [comment]
Great. Just signed and sent the CLA.

**Comment by vnijs** [comment]
FYI Just got the confirmation email from JJ.

**Comment by vnijs** [comment]
FYI Just got the confirmation email from JJ

**Comment by yihui** [comment]
Okay, could you separate the two things? Ideally let's do one thing per PR, so we can accept one without waiting for the other being revised. As I said, the `dataTableAjax` argument looks fine. Perhaps a name `filter` (or `filterFun`) sounds better than `toJSONfun`.

I'd strongly recommend you to use GIT branches for pull requests in the future, unless you are fairly confident it is a trivial change and will definitely be accepted, otherwise chances are you will have to revise, rebase, force push, and resubmit, which are not good for the master branch. The second commit in this PR could have been avoided by rebasing (cf https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md#pull-requests).

Thanks!

**Comment by vnijs** [comment]
Thanks for the suggestions. This is such a minor change that it would be a lot easier if you add the argument in master. For the filter boxes, removing `form-control` is probably not a great way to implement what I had in mind. When using DT in a shiny app the square boxes (also on `search`) are a bit ugly and inconsistent with the rest of the formatting. I was hoping that this approach might help a bit for you to come up with a better solution :)

**Comment by yihui** [comment]
Please see http://rstudio.github.io/DT/008-filter.html

**Comment by vnijs** [comment]
I was just looking at this. Thanks

**Comment by vnijs** [comment]
Really nice enhancements @yihui. The sliders for integer values work great. Thank you!

I haven't had a chance to try-out customizing the server-side filtering etc. but for now there are just two remaining items on my DT _wish-list_. 1. have stateSave working for column filters and 2. css fix for slider location in wide tables (see screen shot). For 2, as you can see, the slider is far from the active cell in these cases. This does not happen for factors by the way.

screen shot 2015-05-30 at 3 36 14 pm

**Comment by yihui** [comment]
I'll work on 1 this evening. I'll have to think more about 2.

**Comment by vnijs** [comment]
Thanks. FYI I just noticed something that happens for numbers with > 2 decimal places. As you can see in the 1st screenshot the slider shows all (?) decimals. Then when you use the slider (2nd screenshot) the numbers are formatted to 2 decimal places. Perhaps this is what you want if you are looking for min and max although in the 2nd screenshot max is also formatted to 2 decimals but was not changed. Using 2 decimals in the initial slider might be (slightly) preferred.

screen shot 2015-05-30 at 4 00 22 pm

screen shot 2015-05-30 at 4 00 36 pm

**Comment by yihui** [comment]
Could you try to file a new issue as you find new problems? Otherwise I feel I can never close an issue since it often quickly diverges to several different issues, and the size of the bullet points just keeps on growing in the response...

For your wish list:

1. I thought a while and sorry I don't have a good solution yet.
2. Same as #73. Fixed. Again, please try not to blend different issues into one thread.

For this particular case, I guess it does not hurt much, but I discovered a much worse bug: when all numbers are smaller than 0.001, the range will be rounded to `[0,0]`, which will fail the slider...

**Comment by vnijs** [comment]
Will do. Thanks

**Pull request closed without merging**
