### PR TITLE
add plugin "scientific"

### PR DESCRIPTION
**Pull request by shutinet**
Sort numbers in scentific notation.

### CODE REVIEW

**Comment by shrektan** [comment]
Thanks, looks good to me. Would you mind add an item in NEWS? In addition, adding a small useful example as a comment in this issue ticker will be beneficial.

**Comment by shutinet** [comment]
Yes of course!
`DT::datatable(data.frame(A = c("2.317e+08", "6.399e+07", "3.086e+08", "9.034e+06")), plugins = "scientific")`

**Comment by shrektan** [comment]
@shutinet Sorry, but the example looks not very useful to me, as I find DT will sort the column A as if they were numeric values already, even without the plugin "scientific"...

Any better example to illustrate the usefulness of this plugin?

Thanks.

```r
df <- data.frame(
  A = c("2.317e+08", "6.399e+07", "3.086e+08", "9.034e+06")
)
df[] <- df[order(as.double(df$A)),]
df$B <- 1:4
DT::datatable(df)
```

image

**Comment by shutinet** [comment]
@shrektan oh i found why: this is the deactivation of the server side of tables on shiny apps which allow this sorting and not the use of this plugin... sorry for the inconvenience, i clause this PR.

**Comment by shrektan** [comment]
You're welcome. Looking forward to your next PR 😄

**Pull request closed without merging**
