### PR TITLE
Extract and export server-side searching functions

### PR DESCRIPTION
**Pull request by mikmart**
The linked filter feature requested in #587 would benefit from being able to redo server-side searches.

This PR extracts and exports the global and column searching parts from the internal `dataTablesFilter()` function as `doGlobalSearch()` and `doColumnSearch()` respectively, letting users run modified searches. This is useful in conjunction with the new `updateFilters()` for setting filter limits based on the values that would be available if all _other_ filters were applied.

Here's an example app demonstrating the kind of functionality enabled by this feature:

``` r
library(shiny)
library(DT) # remotes::install_github("mikmart/DT@export-search")
library(dplyr)

# Adverse events data from a fake clinical trial
file <- file.path(tempdir(), "adae.xpt")
if (!file.exists(file)) {
  url <- "https://github.com/RConsortium/submissions-pilot1-to-fda/raw/main/m5/datasets/rconsortiumpilot1/analysis/adam/datasets/adae.xpt"
  curl::curl_download(url, file, quiet = FALSE)
}
adae <- haven::read_xpt(file)

tbl <- adae %>% 
  transmute(
    USUBJID = factor(USUBJID),
    AESEQ = as.integer(AESEQ),
    AEDECOD = factor(AEDECOD),
    AESOC = factor(AESOC)
  )

ui <- fluidPage(
  DTOutput("table")
)

server <- function(input, output, session) {
  output$table <- renderDT(tbl, filter = "top")
  
  filterable_sets <- eventReactive(input$table_search_columns, {
    # Get separately filtered indices
    fi <- Map(doColumnSearch, tbl, input$table_search_columns)
    
    # Find what rows others leave available
    ai <- lapply(seq_along(fi), function(j) Reduce(intersect, fi[-j]))
    
    # Get the corresponding data
    lapply(Map(`[`, tbl, ai), function(x) {
      if (is.factor(x)) droplevels(x) else x
    })
  })
  
  proxy <- dataTableProxy("table")
  observeEvent(filterable_sets(), {
    updateFilters(proxy, filterable_sets())
  })
}

shinyApp(ui, server)
```

### CODE REVIEW

**Review by yihui — APPROVED** [review]
From the experience of the past PRs, I guess I can just trust your PRs now, since you've been very meticulous. I didn't review this PR on a line-by-line basis, but it looks good to me overall. If I fail to recognize any potential problems, we can definitely amend this PR later. Thanks!

**Comment by mikmart** [comment]
Thank you for the trust @yihui!

**Comment by mikmart** [comment]
@philippleppert you can use `doGlobalSearch()` to find the rows that the global search box filters out, and also exclude those values from each filterable set. Modifying the example here, you'd add something like:

``` r
    # Account for global search
    gi <- doGlobalSearch(as.data.frame(tbl), input$table_search)
    ai <- lapply(ai, intersect, gi)
```

(There's a bug in `doGlobalSearch()` at the moment which makes it not work with tibbles, so need `as.data.frame()`.)

You also need to make sure `filterable_sets()` takes a reactive dependency on the search box input:

``` r
  filterable_sets <- eventReactive(c(input$table_search, input$table_seach_columns), {
```

**Comment by philippleppert** [comment]
@mikmart this works fine! thank you so much 👍

**Pull request merged**
