### PR TITLE
Editing cells with text areas

### PR DESCRIPTION
**Pull request by stla**
Usage example:

```
    datatable(
      iris[1:5,], 
      editable = list(target = "cell", numeric = 1, area = 5)
    )
```

`area` can be a vector of indices or `"all"`.

DTareaedit

### CODE REVIEW

**Comment by stla** [comment]
@yihui This pull request is ready. It contains the pull request "Numeric editing".

**Review by yihui — APPROVED** [review]
I've only briefly reviewed this PR, and it looks good to me. I guess we can merge it after you resolve the git conflicts. Thanks!

**Comment by stla** [comment]
Hi @yihui , I resolved the conflict.

**Comment by yihui** [comment]
@stla I wonder if you have received my email on Aug 23 sent to your yahoo.fr email address.

**Comment by stla** [comment]
@yihui Ah no, I don't use this address anymore. I will check. Now I'm using **laurent_step@outlook.fr**.

**Pull request merged**
