### PR TITLE
Allow integer and character columns in `updateFilters()`

### PR DESCRIPTION
**Pull request by mikmart**
Part of #971.

This PR allows integer and character columns to be included in the data whose filters are being updated.

I also added an example app to demonstrate (and test) `updateFilters()`.

### CODE REVIEW

**Review by yihui — APPROVED** [review]
Looks good. Thank you!

**Comment by yihui** [comment]
Oops, we have got git conflicts here after merging the other PRs. Could you resolve the conflicts? Thanks!

Please also add a bullet to `NEWS.md` for these PRs. You don't need to mention too much detail. You may also add yourself as a `ctb` to `DESCRIPTION`.

**Comment by mikmart** [comment]
Yeah, sorry about the PR barrage :D I thought one of them might lead into a merge conflict. I'll fix it shortly, and update NEWS.

**Review by yihui — APPROVED** [review]
Perfect. Thanks again!

**Pull request merged**
